CLI:
  TYPE: [TL1,SSH,TELNET] # SSH,TELNET
  PORTS:
    SSH: 22
    TELNET: 23
    TL1: 3082
LOGGING:
  LEVEL: DEBUG  # DEBUG/INFO
DEBUG_ENABLED: FALSE  # TRUE/FALSE
DRIVER:
  PORT_MODE: PHYSICAL  #LOGICAL/PHYSICAL